#pragma once

#define WINDOW_LENGTH
#define WINDOW_WIDTH

#define ENEMY_SPEED 0.5
#define ENEMY_RATE 4
#define ENEMY_HEIGHT 15

#define CLASSIC_TOWER_PRICE_BUILD 5
#define CLASSIC_TOWER_START_RANGE 3
#define CLASSIC_TOWER_START_RELOAD 2
#define CLASSIC_TOWER_START_DAMAGE 1
//////////////////////////
#define MAGIC_TOWER_PRICE_BUILD 10
#define MAGIC_TOWER_START_RANGE 3
#define MAGIC_TOWER_START_RELOAD 2
#define MAGIC_TOWER_START_DAMAGE 1

#define MAGIC_TOWER_EFFECT_TYPE Effect::POISONING
#define MAGIC_TOWER_EFFECT_TIMELEFT 10
#define MAGIC_TOWER_EFFECT_POWER 1
//////////////////////////
#define POISON_TRAP_PRICE_BUILD 6
#define POISON_TRAP_START_RELOAD 2
#define POISON_TRAP_START_DAMAGE 0

#define POISON_TRAP_EFFECT_TYPE Effect::POISONING
#define POISON_TRAP_EFFECT_TIMELEFT 4
#define POISON_TRAP_EFFECT_POWER 1
